name: Delete Stale Branches

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *" # Runs nightly at midnight UTC

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Delete stale branches
        run: |
          git branch | grep "^  integration-test-" | xargs git branch -d
          git branch -r | grep 'origin/integration-test-' | sed 's/origin\///' | xargs -I {} git push origin --delete {}
