name: Delete Stale Branches

on:
  workflow_dispatch:

  push:
    branches:
      - master

  schedule:
    - cron: "0 0 * * *" # Runs nightly at midnight UTC

jobs:
  delete-stale-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all branches
        run: git fetch

      - name: Delete stale branches
        run: git branch -r | grep 'origin/integration-test-' | sed 's/origin\///' | xargs -I {} git push origin --delete {}
